spring:
  application:
    name: paymentservice

  data:
    mongodb:
      uri: mongodb://localhost:27017/paymentservice_db
      auto-index-creation: false

  liquibase:
    change-log: classpath:db/changelog/change-master.xml
    enabled: true
    url: mongodb://localhost:27017/paymentservice_db

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: payment-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

random:
  number:
    api:
      url: https://www.randomnumberapi.com/api/v1.0/random?min=1&max=100&count=1

server:
  port: 8084
