version: '3.8'

services:
  auth-db:
    image: postgres:15
    container_name: auth-postgres
    environment:
      POSTGRES_DB: authservice_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567
    ports:
      - "5434:5432"


  auth-service:
    build: .
    container_name: authentication-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      SPRING_SECURITY_JWT_SECRET: ${SPRING_SECURITY_JWT_SECRET}
      SPRING_SECURITY_JWT_ACCESS_TTL: ${SPRING_SECURITY_JWT_ACCESS_TTL}
      SPRING_SECURITY_JWT_REFRESH_TTL: ${SPRING_SECURITY_JWT_REFRESH_TTL}
    depends_on:
      - auth-db

