name: PaymentService CI

on:
  push:
    branches: ["main"]
  pull_request:
    types:
      - closed
    branches:
      - "main"
    paths:
      - 'paymentservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Build paymentservice
        run: | 
          cd paymentservice
          chmod +x gradlew
          ./gradlew clean build -x test
          
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Test paymentService
        run: |
          cd paymentservice
          chmod +x gradlew
          ./gradlew test

  code-analysis:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Spot bugs analysis
        run: |
          cd paymentservice
          chmod +x gradlew
          ./gradlew spotbugsMain
        continue-on-error: true
      - name: Upload SpotBugs report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: spotbugs-report-paymentservice
          path: paymentservice/build/reports/spotbugs/

  artifact-creation:
    runs-on: ubuntu-latest
    needs: [ build, test, code-analysis ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
      - name: Build Jar
        run: |
          cd paymentservice
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: set up docker build
        uses: docker/setup-buildx-action@v3

      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: ./paymentservice
          push: false
          tags: paymentservice:latest

      - name: upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: paymentservice-jar
          path: paymentservice/build/libs/paymentservice.jar